### ISSUE TITLE
sha256 jet program satisfaction fails

### ISSUE THREAD

**Issue by sanket1729** [BlockstreamResearch/simfony#107]
```rust
fn main() {
    let ctx: Ctx8 = jet::sha_256_ctx_8_init();
    let ctv_hash: u256 = jet::sha_256_ctx_8_finalize(ctx);
    ()
}
```

If I try to satisfy this with empty witness, the program says 
```
Jet failed during execution
```

I think the related to cargo test failing on the current master

**Comment by sanket1729** [comment]
I am running cargo test on `884b00e2dc36b3515b7eb9a83478bb3382bbd4f5`

```

failures:

---- tests::type_alias stdout ----
thread 'tests::type_alias' panicked at src/lib.rs:395:31:
Unexpected error: Jet failed during execution

---- tests::ctv stdout ----
thread 'tests::ctv' panicked at src/lib.rs:395:31:
Unexpected error: Jet failed during execution
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::cat stdout ----
thread 'tests::cat' panicked at src/lib.rs:395:31:
Unexpected error: Jet failed during execution

---- tests::hash_loop stdout ----
thread 'tests::hash_loop' panicked at src/lib.rs:395:31:
Unexpected error: Jet failed during execution

---- tests::ctv_2 stdout ----
thread 'tests::ctv_2' panicked at src/lib.rs:395:31:
Unexpected error: Jet failed during execution


failures:
    tests::cat
    tests::ctv
    tests::ctv_2
    tests::hash_loop
    tests::type_alias
```

**Comment by uncomputable** [comment]
I cannot reproduce the error on my end, even after resetting `Cargo.lock`. It seems like all examples with empty witness are failing on your end. Even the OP_CAT example is failing, although it is just pushing some tuples around. Strange.

**Comment by sanket1729** [comment]
Strange. could be because I am trying on a Mac work machine and the bindings are acting funky.

**Comment by sanket1729** [comment]
I will try on a linux box. Maybe that is the issue

**Comment by sanket1729** [comment]
https://github.com/BlockstreamResearch/rust-simplicity/issues/257 . Tracking this here.
